app:
  name: CurrencyExchangeApp
  port: :3000
# 数据库相关配置
database:
    host: localhost
    port: 3306
    user: tester
    pass: 123456
    name: currency_exchange_db
    MaxIdleConns: 11
    MaxOpenConns: 110
Redis:
  addr: "127.0.0.1:6379"
  db: 0
  password: ""
